system76driver/actions.py
wilp14: don't add i915.alpha_support=1 when NVIDIA GPU is present
=> Wilp14 i915 artful

system76-firmware-dialog
=> Firmware dialog

debian/control, debian/system76-driver.postinst
Add gnome-shell-extension-system76-power (and therefore system76-power as well) as depends for system76-driver
=> Add system76-power as depends

debian/changelog, system76driver/actions.py
Fixes https://github.com/pop-os/system76-driver/issues/55
=> 2nd patch to keep up with kernelstub

debian/control, system76-daemon, system76driver/actions.py, system76driver/daemon.py, system76driver/products.py
This calculates total power draw on oryp4 and attempts to reduce CPU power to address overdraw on battery
=> oryp4: manage processor TDP to maintain stability and optimize performance

debian/changelog, system76driver/__init__.py, system76driver/model.py, system76driver/products.py, system76driver/tests/test_products.py
Need to check if `headset_fixup` needs to be added.
=> Add meer4 bionic

debian/changelog, system76driver/__init__.py, system76driver/model.py, system76driver/products.py, system76driver/tests/test_products.py
Need to check if headset_fixup needs to be added.
=> Meer4 cosmic

debian/changelog, system76driver/__init__.py, system76driver/model.py, system76driver/products.py, system76driver/tests/test_products.py
Still need to test to ensure other actions do not need to be included. Will also need to add product to firmware.py.
=> WIP: Add galp3-c to bionic driver

debian/changelog, system76driver/__init__.py, system76driver/model.py, system76driver/products.py, system76driver/tests/test_products.py
Still need to test to ensure other actions do not need to be included.
=> WIP: Add galp3-c to cosmic driver

debian/changelog, system76driver/data/gtk3.glade, system76driver/firmware.py, system76driver/model.py, system76driver/products.py, system76driver/tests/test_products.py
Add oryp5 to firmware flashing and supported models
=> oryp5 disco

debian/changelog, system76driver/model.py, system76driver/products.py, system76driver/tests/test_products.py
=> Add thelio-major-b1.1 and thelio-major-b2

debian/changelog, system76driver/__init__.py, system76driver/actions.py, system76driver/products.py
Add snd_hda_intel.probe_mask=1 for oryp5
=> Add snd_hda_intel.probe_mask=1 for oryp5

debian/changelog, system76driver/__init__.py, system76driver/actions.py, system76driver/tests/test_actions.py
Improvements for kernelstub option modifications
=> Kernelstub Improvements

debian/changelog, system76-firmware-dialog
This improves firmware instructions on newer firmware. Related to https://github.com/system76/docs/commit/69147c0ae0634b87f6c618c4877cd4f328603941
=> Firmware instructions

system76driver/firmware.py
=> Allow ME to be disabled when checking for firmware updates

system76driver/util.py
This fixes the OS Version reported in the systeminfo.txt file when creating logs.
=> Corrects OS Version report

debian/changelog, make-release.py, system76driver/__init__.py, system76driver/actions.py, system76driver/model.py, system76driver/products.py, system76driver/tests/test_products.py
Adds lemp9 with no patches and meer5 with audio patch
=> Add lemp9 and meer5

debian/changelog, debian/control, system76driver/__init__.py
nvidia-driver-435 is just a virtual package installing nvidia-driver-440
=> Update to nvidia-driver-440

debian/changelog, system76driver/__init__.py, system76driver/model.py, system76driver/products.py, system76driver/tests/test_products.py
Rebase and run ./make-release.py when approved
=> Add serw12 and thelio-r2

debian/changelog, system76driver/__init__.py, system76driver/model.py, system76driver/products.py, system76driver/tests/test_products.py
Merge and run ./make-release.py after approval. This also removes the test on PRODUCTS length, it is meaningless.
=> Add addw2 and gaze15

debian/changelog, system76driver/products.py, system76driver/util.py
This PR adds the following:
- Logs /etc/fstab
- Logs /etc/apt/sources.list and /etc/apt sources.list.d/
=> Adds more logging

debian/changelog, debian/control, system76driver/__init__.py
This package will set power limits for the serw12
=> Recommend amd-ppt-bin in system76-driver-nvidia 

debian/changelog, system76driver/__init__.py, system76driver/model.py, system76driver/products.py
Merge and run make-release.py when approved
=> Add bonw14

debian/changelog, system76driver/__init__.py, system76driver/util.py
This adds the following new log options:
lsblk -f
df -h
as requested by Support.
=> Add new logs

debian/changelog, system76driver/__init__.py, system76driver/model.py, system76driver/products.py
Rebase and make-release when approved
=> Add thelio-major-b3

debian/changelog, system76driver/__init__.py, system76driver/actions.py, system76driver/products.py
Rebase and make release when approved
=> thelio-r2 audio fixup

debian/changelog, debian/system76-driver-nvidia.postinst, quirks/system76-nvidia-quirks-thelio-massive-b1
Adds a quirk to fix issue with massive-b1 and Nvidia GPUs and fixes https://github.com/system76/testing/issues/281
=> Added quirk for thelio-massive-b1 and Nvidia GPUS

debian/changelog, system76driver/__init__.py, system76driver/util.py
This PR adds uptime output for support to have per JJ on the Happiness Team.
=> Add uptime

debian/changelog, system76driver/__init__.py, system76driver/model.py, system76driver/products.py
=> Add gaze16

debian/changelog, debian/control, system76driver/__init__.py, system76driver/userdaemon.py
This sets the microphone device when the correct USB audio codec is found
=> thelio-major-r2.2

debian/changelog, system76driver/__init__.py, system76driver/userdaemon.py
Minor improvement to #224. Fixes mic-in on Major r2.2, and retains line-in fix from #224
=> Re major r2.2 line in

debian/changelog, debian/control, system76driver/__init__.py
Related to https://github.com/pop-os/nvidia-graphics-drivers/pull/136
=> Allow either nvidia-driver-510 or nvidia-driver-470 to be installed

debian/changelog, system76-driver, system76driver/__init__.py, system76driver/util.py
This should fix issues on 22.04
=> Use uname function from os instead of distro

debian/changelog, debian/control, system76driver/__init__.py
This allows NVIDIA driver 515 to be installed.
=> Support nvidia-driver-515

lib/systemd/system-sleep/system76-driver_bluetooth-suspend
Updates https://github.com/pop-os/system76-driver/pull/242 with the new fixes from https://github.com/pop-os/default-settings/pull/145 for Ubuntu.
Co-authored-by: Peter Bui [pbui@github.bx612.space](mailto:pbui@github.bx612.space)
=> Bluetooth suspend workaround

debian/changelog, debian/control, system76driver/__init__.py, system76driver/data/gtk3.glade, system76driver/gtk.py, system76driver/util.py
The reset button appears not necessary by California title 20
regulations. By directive of @WatchMkr we are removing the button.
Reverts 60eb4ee7217af89d06019806ef0208f47d6baae9
=> Remove power reset

debian/changelog, debian/system76-driver.install, system76-virtual-hub, system76driver/__init__.py, system76driver/model.py, system76driver/products.py
Added thelio-mega-r3 to TABLES in system76driver/model.py and
PORODUCTS in system76driver.
Also added a suspend hook to remove some usb virtual devices
before suspend and scan them back in on resume in order to
prevent the system from spontaneously waking from suspend.
=> Add new model thelio-mega-r3

debian/changelog, debian/control, system76driver/__init__.py
Requires https://github.com/pop-os/system76-io-dkms/pull/14
Related to https://github.com/pop-os/system76-power/pull/438
=> Only require some dependencies on amd64

debian/changelog, system76driver/__init__.py, system76driver/actions.py, system76driver/products.py
This disables suspend on astra
=> thelio-astra-a1: mask suspend

debian/changelog, system76driver/__init__.py, system76driver/model.py, system76driver/products.py
Was done in Noble here: https://github.com/pop-os/system76-driver/pull/319
=> Add thelio-r5 for Jammy

bump-version.py, debian/changelog, debian/control, make-release.py, system76driver/__init__.py
Requires https://github.com/pop-os/nvidia-graphics-drivers/pull/227
=> Support NVIDIA 570 driver (22.04)
