system76driver/actions.py, system76driver/products.py
For "wilp14", add "i915.alpha_support=1" flag to /etc/default/grub
=> Add new actions.i915_alpha_support class, use by 'wilp14'

system76driver/firmware.py
If the ME switch is available, the ME must be disabled to set the changelog entry to "disabled"
This should fix spurious firmware update notifications
=> Do not show upstream ME version as disabled if the user has chosen to enable it

system76driver/util.py
Without limiting journalctl to a timeframe, I have received a 650MB journalctl output, which is a bit unwieldy.
=> Update journalctl to provide only the last day of logs

system76driver/actions.py
Split function does not need to be called here, and causes the error #52 .
I wasn't sure if I should remove the `split()` from line 409. `get_current_cmdline` seems different enough, I figure we can make that change if another regression is reported.
=> Don't split() on a list, fix #52

system76-driver.desktop
I assume 2.7.3 was the system76-driver application version, but the
Version tag in .desktop files is actually supposed to refer to the
version of the Desktop Entry specification being used, to make backwards
compatibility support easier. Sort of like how XML files specify which
XML version they're using at the beginning of every document.
The Version entry key is described here:
<https://specifications.freedesktop.org/desktop-entry-spec/1.1/ar01s05.html>
The highest version of the Desktop Entry spec is 1.2alpha, but since
it's "alpha" I decided to go with the previous release, 1.1. Not that
there have been many significant changes at all so far since 1.0.
=> Version tag in .desktop file refers to version of Desktop Entry spec

system76driver/actions.py, system76driver/products.py
Yet another place that needs a fix for pop-os/system76-power#71
It turns out that this module needs to be disabled universally, as it causes hangs even in NVIDIA mode
=> Blacklist i2c-nvidia-gpu on oryp5

bump-version.py
There's no reason one should need bazaar setup to run bump-version.py which uses git.
=> Update bump-version.py to not require bzr

debian/changelog, debian/control
This fixes the brightness on the addw1
The new daemon can be seen here: https://github.com/pop-os/system76-oled
When a new ISO is built, system76-oled will need to be added to the pool
=> Depend on system76-oled for brightness support on addw1

debian/changelog, system76driver/__init__.py, system76driver/products.py
This also needs to be done on the gaze14 to avoid boot delays on 18.04
=>  Blacklist i2c_nvidia_gpu on gaze14 

debian/changelog, debian/rules, debian/system76-driver.install, system76-apt-preferences, system76driver/__init__.py
This will, similar to the Pop APT preferences, prevent overriding packages from the system76-dev PPAs. This must be merged after https://github.com/pop-os/nvidia-graphics-drivers/pull/21 is released and the custom kernels are removed
=> APT preferences

debian/changelog, make-release.py, system76driver/__init__.py
Identical to the change made to the bump-release script, eliminating the reliance on bzr for releasing a new version of the system76-driver.
=> Update make-release script to not rely on bzr

debian/changelog, debian/system76-driver.install, system76-thunderbolt-reload, system76driver/__init__.py
This is a workaround that will, on the darp6 and galp4, reload the thunderbolt driver on suspend and resume.
=> Reload thunderbolt driver to avoid hangs

bump-version.py, debian/changelog, debian/control, make-release.py, system76-driver, system76driver/__init__.py, system76driver/gtk.py, system76driver/util.py
- Updates platform to distro to fix this issue:
https://github.com/pop-os/system76-driver/pull/137
- Updates the bump-version.py and make-release.py to include focal.
- Updates the debian/control with python3-distro and dh-python.
- Updates the driver version to 20.04.1.
=> Focal support

bump-version.py, debian/changelog, system76driver/__init__.py, system76driver/actions.py, system76driver/tests/test_gtk.py
`splitlines()` strips the line endings, causing `get_isneeded()` to always return true. This caused the setting to always be appended to the PulseAudio config file when system76driver was run.
Fixes: 345cd929d042f ("Load USB audio S/PDIF output device")
=> actions: Fix string comparison involving newline

debian/changelog, system76driver/__init__.py, system76driver/actions.py, system76driver/products.py
This PR adds a new action for adding i8042.nomux to the kernel boot parameters, and adds that action to the list for gaze14 to apply.
(I went with a new action rather than re-using the oryp2 action because i8042.reset isn't needed for this issue based on testing, and I would have needed to modify the comment and label for the oryp2 touchpad action to be more vague or include multiple items. It seems cleaner to have this as its own action.)
- Installed fresh copy of Pop 20.04
- Added repo, installed updates-- saw the action get applied
- Rebooted, ran `dmesg`, observed `i8042.nomux` was present in kernel boot parameters
- Confirmed keyboard after suspend/resume issue does not occur.
=> Add i8042.nomux to kernel boot parameters on gaze14

system76-nm-restart
The systemd service for NetworkManager was renamed so the old mapping does not work any longer. This updates the command to systemd specs.
service network-manager restart
Failed to restart network-manager.service: Unit network-manager.service not found.
=> update restart command to systemd usage

system76driver/actions.py, system76driver/products.py
It seems non-optimal to write this to `/usr`, but Firefox doesn't read such configuration from a subdirectory of `/etc`.
The replaces the use of `xrender`, which was enabled by https://github.com/pop-os/default-settings/pull/96.
Note for this to take effect, `xrender` should be disabled.
=> Enable WebRender on the serw12

debian/changelog, system76driver/__init__.py, system76driver/userdaemon.py
Do only the *.1 revisions use ALC1220VBDT as the card name?
Does the major-r2 need its name changed back also?
=> Set card name to 'Audio' for thelio-mega-r1

debian/changelog, system76driver/__init__.py, system76driver/actions.py, system76driver/products.py
This PR will persistently set the NVIDIA driver's `ForceFullCompositionPipeline` option on serw12 by placing a command in `/etc/profile` to enable the option at login. After enabling it this way, it continues to stay enabled when adding, removing, or reconfiguring displays.
Since the `ForceFullCompositionPipeline` not only fixes input lag in LibreOffice/Terminal but also fixes the scroll lag in Firefox's default software renderer, this PR also unsets the WebRender override that was previously being used in order to keep the diff minimal. (We now set only the `frame_rate` option for Firefox, since that is still needed for full performance with the default renderer.)
Tested and confirmed working on lab serw12:
- All config modifications are made as intended.
- Re-configuring …
=> serw12: set NVIDIA ForceFullCompositionPipeline (and unset Firefox WebRender)

debian/changelog, system76driver/__init__.py, system76driver/actions.py, system76driver/products.py
This works around a driver bug when unplugging the AC adapter while the NVIDIA GPU is off
=>  galp5: Set NVIDIA dynamic power to recommended value

debian/changelog, system76driver/__init__.py, system76driver/actions.py, system76driver/products.py
Currently, the gaze15 (NH50DB) keyboard sometimes doesn't work after suspend/resume and requires an additional suspend/resume to bring back (able to recreate after 1-3 suspends.) After this change, it passed 50 suspend/resumes with no keyboard failures.
serw12 was also experiencing the same problem occasionally, and no longer has the issue after applying this action.
=> Add i8042.nomux option to gaze15 and serw12

debian/changelog, system76driver/__init__.py, system76driver/actions.py, system76driver/products.py
This ought to fix X crashes on Ubuntu 20.04
=> oryp6: Add i915 driver to initramfs

debian/control, debian/system76-driver.gsettings-override
The gsettings override will be added to the `system76-wallpapers` package instead. This will allow users to remove the `system76-wallpapers` package (or install the driver with `--no-recommends`) if they don't want it.
=> Move wallpapers to recommends and remove gsettings override

debian/changelog, system76driver/__init__.py, system76driver/util.py
This PR adds the following files to the driver which is helpful for support and engineering/QA:
- /var/log/apt/history.log
- /var/log/apt/history.log.1.gz
- /var/log/apt/term.log
- /var/log/apt/term.log.1.gz
Tested on a `galp3-b` and a `lemp9`. One was running Ubuntu 20.04 LTS and the other running Pop 20.10.
=> Add apt/history logs

debian/changelog, debian/control, system76driver/__init__.py, system76driver/actions.py, system76driver/products.py
When NVIDIA driver 460 is available, https://github.com/pop-os/nvidia-graphics-drivers/pull/85, this can be merged.
=> Remove NVIDIA dynamic power override

debian/changelog, debian/control, system76driver/__init__.py, system76driver/util.py
This adds the following to the driver:
- updates debian/control to include `lm-sensors` to the deps 
- adds the sensors command to the dump command section
Tested on Pop 20.10.
=> Add sensor data

debian/changelog, system76driver/__init__.py, system76driver/actions.py, system76driver/products.py
Setting it to 10000 allows Samsung drives to continue to enter PS3 and PS4, but prevents the WD Blue drive from entering these power states.
=> Pang10 wd blue

debian/changelog, system76driver/__init__.py, system76driver/actions.py, system76driver/products.py
The `snd_hda_intel.power_save=0` option doesn't actually get audio working (accessing the systemd-boot menu to add the option manually is what got audio working while testing that option), so this PR removes that action from the meer6.
This PR also adds a new action to run `xrandr --output DP-1 --set audio on` on every graphical login using `/etc/xprofile`.
The meer6 refers to the physical HDMI 1 port as `DP-1`, and the physical HDMI 2 port as `HDMI-1`. The HDMI 2 port appears to have working audio without any tweaking needed, while the HDMI 1 port needs the above command to have working audio on boot. (Other actions that trigger xrandr, such as replugging the display or switching the display input, also get audio working, but the above command should make it happen automatically.)
I will …
=> Fix meer6 audio

debian/changelog, system76driver/__init__.py, system76driver/actions.py, system76driver/products.py
=> meer5: Fix audio on revision without headphone jack

debian/changelog, system76driver/__init__.py, system76driver/actions.py, system76driver/tests/test_actions.py
Fixes #207.
Currently, the driver crashes if the parent directory of a config file being written with a FileAction doesn't exist. If this was intentional, then I could see the action just being skipped, but since it actually crashes, it doesn't seem intentional.
Thinking about whether an action should be skipped or performed anyway if the parent directory doesn't already exist, it seems like we'd want config files to be installed anyway, in case the user later installs the component we're trying to configure. In cases where the file is overwritten by the package being installed (such as with the pulseaudio file in #207), the driver will need to be reconfigured after the package is installed either way, so it doesn't really make a difference.
If this seems like a bad idea for any reason, …
=> FileAction: Create parent directories if necessary

debian/changelog, system76driver/__init__.py, system76driver/actions.py, system76driver/products.py
This should fix https://github.com/pop-os/linux/issues/45
=> lemp9: Add intel_idle.max_cstate=4 kernel parameter to fix freezes 

debian/changelog, debian/system76-driver.install, lib/systemd/system-sleep/system76-driver_bluetooth-suspend, system76driver/__init__.py
This script will run if the pop-default-settings is not present to ensure Ubuntu systems also get the bluetooth suspend workaround
=> Bluetooth suspend workaround

system76driver/products.py
This fixes the plymouth decrypt screen on mira-b3 on the 5.19 kernel
=> mira-b1: add nvidia drm to initramfs

debian/changelog, debian/control, system76driver/__init__.py
nvidia-driver-510 doesn't work with Linux 6.0.2. Removing it as an optional dependency probably makes more sense than fixing it at this point, since nvidia-driver-515 has been stable for a while.
=> Remove nvidia-driver-510 as an optional dependency

debian/changelog, system76driver/__init__.py, system76driver/actions.py, system76driver/products.py
These models should always use I2C HID, but sometimes try to initialize using the PS/2 interface. Blacklist the module until all issues in firmware can be resolved.
NOTE: This change will need to be reverted when testing firmware changes such as https://github.com/system76/ec/pull/325.
=> Blacklist psmouse on TGL and ADL

debian/changelog, debian/system76-driver.install, system76-atlantic-reload, system76driver/__init__.py
removes atlantic 10G ethernet pci bridge pre suspend, then re-scans it back in post suspend to avoid hanging during suspend or on resume.
Workaround for Bugzilla report:  https://bugzilla.kernel.org/show_bug.cgi?id=217260
=> reload atlantic pci bridge to avoid suspend hang

system76driver/actions.py
Hey,
Debian testing/sid and Gentoo now have Python 3.12 by default.  One of the changes in 3.12 is that invalid string escape sequences now produce a SyntaxWarning (and in some future Python this will become an error).  There are some invalid escapes in actions.py that cause the user-visible messages below.  This PR fixes these two.  I don't see warnings for any others in my build log.
Setting up system76-driver (20.04.91-0kh13.1) ...
WARNING invalid sys_vendor: 'Dell Inc.'
WARNING invalid product_version: None
/usr/lib/python3/dist-packages/system76driver/actions.py:46: SyntaxWarning: invalid escape sequence '\['
LSPCI_RE = re.compile('^(.+) \[(.+)\]$')
/usr/lib/python3/dist-packages/system76driver/actions.py:1132: SyntaxWarning: invalid escape sequence '\:'
LIMIT_TDP_SCRIPT = …
=> Fix some invalid string escapes which are now warnings in Python 3.12

debian/changelog, system76driver/__init__.py, system76driver/model.py, system76driver/products.py
Applies https://github.com/pop-os/system76-driver/pull/301 and the subsequent release to the Jammy branch.
=> Cherry-pick Astra commits into master_jammy

debian/changelog, debian/control, system76driver/__init__.py
On x86 systems, nvidia-driver-550 is provided as a transitional package to nvidia-driver-560.
On ARM systems, nvidia-driver-550 is the latest Ubuntu version available.
This ensures both architectures get the latest NVIDIA driver.
=> Bump nvidia driver to 550

debian/changelog, system76driver/__init__.py, system76driver/actions.py, system76driver/products.py
Remove psmouse blacklist on RPL, MTL
PS/2 touchpad is fixed in System76 EC with the following commits:
- system76/ec@d88a175e23f3 Clear PS/2 touchpad status when waiting for write to finish
- system76/ec@5b0766a2099f USe debounce bit and do not use interrupts for touchpad
All systems running system76/firmware-open@9e418a22fffe (2024-06-26) or newer include these changes.
Ref: https://github.com/system76/ec/pull/464
Ref: https://github.com/system76/firmware-open/pull/558
Required firmware releases:
=> Remove psmouse blacklist on RPL, MTL

debian/changelog, system76driver/__init__.py, system76driver/util.py
This adds an additional line for systeminfo.txt which looks like this in the Pop Support Pane:
Kernel Revision: #202405300957~1736980680~22.04~44ea8a9
now the systeminfo.txt from the system76-driver will include it as well, this is useful when we bump the kernel to include a fix like the pang15 but it does not change from the current version such as 6.9.3 so we can see by the hash if it included the fix.
=> Add kernel revision nobuild

debian/changelog, system76driver/__init__.py, system76driver/products.py
PS/2 interface seems to still be problematic. Every boot/resume fails to
initialize the device with:
psmouse serio1: Failed to deactivate mouse on isa0060/serio1: -5
psmouse serio1: Failed to enable mouse on isa0060/serio1
Would be good to check if other models are doing this, or if it's just addw4.
=> addw3,addw4: Re-add psmouse blacklist
